### ISSUE TITLE
Trying to implement on MAC

### ISSUE THREAD

**Issue by WING-user** [pmaillot/wapi#1]
Hi,

I am trying to implement the code on MACOS but it's using the windows.h file which is not on a MAC. Do you have any idea's for it to work?

Regards

**Comment by pmaillot** [comment]
There are library and include files for mac. The test program wtest.c should work in a mac environment as it's a terminal window program. Any other test program that relies on a WIndows GUI... you'd have to port or modify it for a mac.

Another option: run the Windows compiled GUI programs under WINE on your mac.
