### ISSUE TITLE
Wapi.lib

### ISSUE THREAD

**Issue by brilletjuh** [pmaillot/wapi#2]
Hi Patrick,

I was wondering where I could find the actual wapi.lib file.
I can't find it in this repository.

Also, less related, is there a list of all binary hashes or should i just call wGetHash for that?

Thanks in advance,
brilletjuh (Daniel)

**Comment by pmaillot** [comment]
The windows version of the library (libwapi.a) is in the WIndows directory, same for the linux version.

As to the list of the near 30000 hashes... the whole point of wapi is to provide an abstraction layer for them and offer list of tokens that is more conveniently organized for use in applications. 

If you still want the full list, the simplest is to travel the WING dataset tree from its root. Getting to the root of the hierarchy tree is listed in the table p 72 of the wapi document, with code 0xda.

-P.
